/* =====================================================================
   Firebase initialization (shared by every screen).
   Reads firebaseConfig from config.js, starts Firebase, exposes window.db,
   and applies the real-time long-polling setting. Do not edit this file
   unless you know what you are doing - paste your config in config.js.
   ===================================================================== */
(function () {
  window.CONFIG_OK = (typeof firebaseConfig !== "undefined") && firebaseConfig.apiKey !== "PASTE_HERE";
  if (!window.CONFIG_OK) return;
  firebase.initializeApp(firebaseConfig);
  var db = firebase.firestore();
  db.settings({ experimentalAutoDetectLongPolling: true, merge: true });
  window.db = db;
})();
